// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using NagarHawlaGovtPrimarySchool.Models;
using System;

namespace NagarHawlaGovtPrimarySchool.Migrations
{
    [DbContext(typeof(NHGPSContext))]
    [Migration("20180308091038_StudentIDAdded")]
    partial class StudentIDAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NagarHawlaGovtPrimarySchool.Models.Admission", b =>
                {
                    b.Property<int>("AdmissionId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClassName")
                        .IsRequired();

                    b.Property<DateTime>("FatherDOB");

                    b.Property<string>("FatherMobile")
                        .IsRequired()
                        .HasMaxLength(14);

                    b.Property<string>("FatherNID")
                        .IsRequired()
                        .HasMaxLength(17);

                    b.Property<string>("FatherName")
                        .IsRequired();

                    b.Property<int>("FormNo");

                    b.Property<string>("HomeOwnerMobile");

                    b.Property<string>("HomeOwnerName");

                    b.Property<string>("MaternalGrandFatherName")
                        .IsRequired();

                    b.Property<string>("MaternalGrandMotherName")
                        .IsRequired();

                    b.Property<DateTime>("MotherDOB");

                    b.Property<string>("MotherMobile")
                        .IsRequired()
                        .HasMaxLength(14);

                    b.Property<string>("MotherNID")
                        .IsRequired()
                        .HasMaxLength(17);

                    b.Property<string>("MotherName")
                        .IsRequired();

                    b.Property<string>("PaternalGrandFatherName")
                        .IsRequired();

                    b.Property<string>("PaternalGrandMotherName")
                        .IsRequired();

                    b.Property<string>("PermanentDistrict")
                        .IsRequired();

                    b.Property<string>("PermanentPost")
                        .IsRequired();

                    b.Property<string>("PermanentPostCode")
                        .IsRequired();

                    b.Property<string>("PermanentSubDistrict")
                        .IsRequired();

                    b.Property<string>("PermanentVillage")
                        .IsRequired();

                    b.Property<string>("PresentDistrict")
                        .IsRequired();

                    b.Property<string>("PresentPost")
                        .IsRequired();

                    b.Property<string>("PresentPostCode")
                        .IsRequired();

                    b.Property<string>("PresentSubDistrict")
                        .IsRequired();

                    b.Property<string>("PresentVillage")
                        .IsRequired();

                    b.Property<int>("StudentBirthCertificateNo");

                    b.Property<DateTime>("StudentDOB");

                    b.Property<int>("StudentId");

                    b.Property<string>("StudentNameBangla")
                        .IsRequired();

                    b.Property<string>("StudentNameEnglish")
                        .IsRequired();

                    b.HasKey("AdmissionId");

                    b.ToTable("Admitted");
                });

            modelBuilder.Entity("NagarHawlaGovtPrimarySchool.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountType")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
